name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.14.x'
      - name: pod cache
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: firebase emulator cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators/
          key: ${{ runner.os }}-emulator-${{ hashFiles('**/.emulator_version') }}
          restore-keys: |
            ${{ runner.os }}-emulator-
      - name: bundle cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.app/Contents/Developer'
      - name: Setup
        run: make
      - name: Install firebase-tools
        run: npm install -g firebase-tools@latest
      - name: Run Test
        run: scripts/test.sh
